spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=jobuser
spring.datasource.password=jobpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 2-6/3-3/3-4/6-4
server.port=8080
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



# =======================
# JWT ??//6-7
# =======================

# ???? 32 ???256 bit?
jwt.secret=f274a6d44f7e4b459e9e9c1a7b8c2d13

# Access Token ?????????? 900 = 15 ??
jwt.access-seconds=900

# Refresh Token ?????????? 604800 = 7 ?
jwt.refresh-seconds=604800

# ???????????? 60 ?
jwt.clockskew-seconds=60



server.error.include-stacktrace=always

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



#i18n
spring.messages.basename=messages,ValidationMessages
#spring.messages.encoding=ISO-8859-1
spring.messages.encoding=UTF-8

spring.messages.fallback-to-system-locale=false
spring.messages.use-code-as-default-message=true
spring.thymeleaf.cache=false

app.bootstrap.enabled=false
app.bootstrap.token=d8f3e8f3-7f1a-4a3b-9c3a-2f5d1a9f1c22


