# =======================
# Server
# =======================
server.port=8080

# =======================
# Datasource (Docker)
# =======================
spring.datasource.url=jdbc:postgresql://db:5432/jobtracker
spring.datasource.username=jobuser
spring.datasource.password=jobpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =======================
# Logging (Docker / Demo)
# =======================
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO

# 不显示堆栈（Demo 更专业）
server.error.include-stacktrace=never

# =======================
# Thymeleaf
# =======================
spring.thymeleaf.cache=true

# =======================
# i18n
# =======================
spring.messages.basename=messages,ValidationMessages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
spring.messages.use-code-as-default-message=true

# =======================
# JWT (Demo)
# =======================
jwt.secret=${JWT_SECRET:f274a6d44f7e4b459e9e9c1a7b8c2d13}
jwt.access-seconds=900
jwt.refresh-seconds=604800
jwt.clockskew-seconds=60

# =======================
# File Storage (Docker / MinIO)
# =======================
file.s3.endpoint=${FILE_S3_ENDPOINT:http://minio:9000}
file.s3.accessKey=${MINIO_ACCESS_KEY:minioadmin}
file.s3.secretKey=${MINIO_SECRET_KEY:minioadmin}
file.s3.bucket=${MINIO_BUCKET:jobtracker}


# =======================
# Bootstrap
# =======================
app.bootstrap.enabled=false
